EventManager/Areas/Customer/Controllers/EventDetailsController.cs
using System.Net;
using EventManager.DataAccess;
using EventManager.DataAccess.Repository.IRepository;
using EventManager.Models;
using EventManager.Models.ViewModels;
using EventManager.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static EventManager.Utils.TempDataInfos;
using static EventManager.Utils.Enums;

namespace EventManager.Areas.Customer.Controllers
{
    [Area(SD.Role_Customer)]
    public class EventDetailsController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IEmailSender _emailSender;
        private readonly ILogger<EventParticipantsController> _logger;

        public EventDetailsController(ApplicationDbContext dbContext, UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork, IEmailSender emailSender, ILogger<EventParticipantsController> logger)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
            _logger = logger;
        }

        [Authorize]
        public IActionResult Index(string eventId)
        {
            var eventObj = _unitOfWork.Event.Get(x => x.Id == eventId);

            if (eventObj is null)
            {
                return NotFound();
            }

            var eventDetailsVm = new EventDetailsVM
            {
                Event = eventObj,
                IsFull = _unitOfWork.EventParticipant.GetAllFilteredCount(x => x.EventId == eventObj.Id && x.Status == AssignmentStatus.Accepted) >= eventObj.Capacity
            };

            eventDetailsVm.Participants = [.. _unitOfWork.EventParticipant.GetAllFiltered(x => x.EventId == eventId, "User")];

            return View(eventDetailsVm);
        }


        public IActionResult _EventParticipantsTable(string eventId)
        {
            // TODO: In case you came up with better way to refresh 
            var participants = _unitOfWork.EventParticipant.GetAllFiltered(x => x.EventId == eventId, "User").ToList();
            return PartialView("_EventParticipantsTable", participants);
        }

        [HttpPut]
        public async Task<IActionResult> ChangeParticipationStatus(int participationId, int status)
        {
            var assignmentStatus = (AssignmentStatus)status;
            if (!(new[] { AssignmentStatus.Accepted, AssignmentStatus.Reserve, AssignmentStatus.Declined }).Contains(assignmentStatus))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = WrongStatus });
            }

            var participation = _unitOfWork.EventParticipant.Get(x => x.Id == participationId, includes: "Event");
            if (participation?.Event is null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = EventNotFound });
            }

            if (assignmentStatus == AssignmentStatus.Accepted && IsEventFull(participation.Event))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = EventIsFull });
            }
            
            participation.Status = assignmentStatus;
            _unitOfWork.EventParticipant.Update(participation);
            _unitOfWork.Save();

            if (assignmentStatus != AssignmentStatus.Accepted || string.IsNullOrEmpty(participation.UserId))
            {
                return RedirectToAction(nameof(_EventParticipantsTable), new { participation.EventId });
            }
            
            var user = await _userManager.FindByIdAsync(participation.UserId);

            if (user == null || string.IsNullOrEmpty(user.Email))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = EmailNotFound });
            }

            var callbackUrl = Request.Scheme + "://" + Request.Host + Url.Action(nameof(Index), new { eventId = participation.EventId });

            await _emailSender.SendEmailAsync(
                user.Email,
                "Event status information",
                $"Congratulations, you have been accepted to the {participation.Event.Title}. In case you change your mind and want to refuse here is redirection to our website. <a href='{callbackUrl}'>Click here to go to the event</a>."
            );

            return RedirectToAction(nameof(_EventParticipantsTable), new { participation.EventId });
        }
        
        public bool IsEventFull(Event obj)
        {
            return _unitOfWork.EventParticipant.GetAllFiltered(x => x.EventId == obj.Id && x.Status == AssignmentStatus.Accepted).Count() >= obj.Capacity;
        }
    }
}

EventManager/Areas/Customer/Controllers/EventParticipantsController.cs
using EventManager.DataAccess.Repository.IRepository;
using EventManager.Models;
using EventManager.Models.ViewModels;
using EventManager.Utils;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mime;
using static EventManager.Utils.Enums;
using static EventManager.Utils.TempDataInfos;

namespace EventManager.Areas.Customer.Controllers
{
    [Area(SD.Role_Customer)]
    public class EventParticipantsController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<EventParticipantsController> _logger;

        public EventParticipantsController(UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork, ILogger<EventParticipantsController> logger)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var eventsVM = new EventsVM
            {
                UserId = _userManager.GetUserId(User),
                Events = _unitOfWork.Event.GetAll().ToList(),
                EventParticipants = _unitOfWork.EventParticipant.GetAll().ToList()
            };

            return View(eventsVM);
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(string eventId)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user is null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = UserNotFound });
            }

            var selectedEvent = _unitOfWork.Event.Get(e => e.Id == eventId);
            if (selectedEvent is null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = EventNotFound });
            }

            var existingParticipant = _unitOfWork.EventParticipant.Get(ep => ep.EventId == eventId && ep.UserId == user.Id);
            if (existingParticipant is not null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = EventParticipantsAlreadySigned });
            }

            var newParticipant = new EventParticipant
            {
                EventId = eventId,
                UserId = user.Id,
                Status = AssignmentStatus.Applied
            };

            try
            {
                _unitOfWork.EventParticipant.Add(newParticipant);
                _unitOfWork.Event.Update(selectedEvent);
                _unitOfWork.Save();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Exception");
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = EventParticipantsError });
            }

            return Json(new { success = true, message = EventParticipantsSigned });
        }

        [HttpDelete]
        public IActionResult SignOut(string? userId, string? eventId)
        {
            var participant = _unitOfWork.EventParticipant.Get(x => x.UserId == userId && x.EventId == eventId);
            if(participant is null) 
            {
                return Json(new { success = false, message = EventParticipantsNotSignedUp });
            }

            _unitOfWork.EventParticipant.Remove(participant);
            _unitOfWork.Save();

            return Json(new { success = false, message = EventParticipantsSignedOut });
        }
    }
}

EventManager/Areas/Customer/Views/EventParticipants/Index.cshtml
@model EventsVM

<div>
    <h1 class="display-4">Events</h1>
</div>

@if (!Model.Events.Any())
{
    <p>There is no events yet to join</p>
}
else
{
    <table class="table table-hover table-primary table-bordered">
        <thead>
            <tr>
                <th scope="col">Tittle</th>
                <th scope="col">Capacity</th>
                <th scope="col">Date</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>

        <tbody>
        @foreach (var item in Model.Events)
        {
            var isSigned = Model.EventParticipants.FirstOrDefault(x => x.UserId == Model.UserId && x.EventId == item.Id);
            <tr>
                <td>@item.Title</td>
                <td>@(Model.EventParticipants.Count(x => x.EventId == item.Id && x.Status == AssignmentStatus.Accepted))/@(item.Capacity)</td>
                <td>@item.Date.ToString("dd.MM.yyyy")</td>
                <td class="text-center">
                    @if (User.IsInRole(SD.Role_Customer))
                    {
                        if (isSigned is not null)
                        {
                            <button type="button" onclick="signOut('@Model.UserId', '@item.Id')" @Html.DisabledIf(isSigned.Status == AssignmentStatus.Declined) class="btn btn-lg btn-warning">Sign out</button>
                        }
                        else
                        {
                            var isFull = Model.EventParticipants.Count(x => x.EventId == item.Id && x.Status == AssignmentStatus.Accepted) >= item.Capacity;
                            <button type="button" onclick="signIn('@item.Id')" @Html.DisabledIf(isFull) class="btn btn-lg btn-success">Sign in</button>
                        }
                    }
                    <a asp-area="Customer" asp-controller="EventDetails" asp-action="Index" asp-route-eventId="@item.Id" class="btn btn-lg btn-secondary">Details</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
}

@section Scripts {
    <script type="text/javascript">
        const successKey = 'successKey';
        const infoKey = 'infoKey';
        
        $(document).ready(function () {
          successInfo(infoKey, successKey);
        });
    
        function signIn(id) {
            $.ajax({
                type: 'POST',
                url: '/Customer/EventParticipants/SignIn',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                data: { eventId: id },
                success: function (result) {
                    sessionStorage.setItem(successKey,"true");
                    sessionStorage.setItem(infoKey, result.message);
                    location.reload();
                },
                error: function (error) {
                    toastr.error($.parseJSON(error.responseText).message);
                }
            })
        }

        function signOut(userId, eventId) {
            $.ajax({
                type: 'DELETE',
                url: '/Customer/EventParticipants/SignOut',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                data: { userId: userId, eventId: eventId },
                success: function (result) {
                    sessionStorage.setItem(successKey,"true");
                    sessionStorage.setItem(infoKey, result.message);
                    location.reload();
                },
                error: function (error) {
                    toastr.error($.parseJSON(error.responseText).message);
                }
            })
        }
    </script>
}