EventManager/Areas/Admin/Controllers/CalendarController.cs
using EventManager.DataAccess.Repository.IRepository;
using EventManager.Utils;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EventManager.Areas.Admin.Controllers;

[Area(SD.Role_Admin)]
public class CalendarController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly UserManager<IdentityUser> _userManager; 
    
    public CalendarController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
    {
        _unitOfWork = unitOfWork;
        _userManager = userManager;
    }
    
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public JsonResult GetEvents()
    {
        var userId = _userManager.GetUserId(User);
        var events = _unitOfWork.Event.GetAllFiltered(x => x.CreatorId == userId).ToArray();
        
        return Json(events);
    }
}

EventManager/Areas/Admin/Controllers/UserManagmentController.cs
using System.Net;
using EventManager.DataAccess;
using EventManager.DataAccess.Repository.IRepository;
using EventManager.Models;
using EventManager.Models.ViewModels;
using EventManager.Utils;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.WebUtilities;
using System.Text;
using System.Text.Encodings.Web;
using static EventManager.Utils.TempDataInfos;

namespace EventManager.Areas.Admin.Controllers
{
    [Area(SD.Role_Admin)]
    public class UserManagmentController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IUserStore<IdentityUser> _userStore;
        private readonly IUserEmailStore<IdentityUser> _emailStore;
        private readonly IEmailSender _emailSender;
        private readonly ApplicationDbContext _dbContext;


        public UserManagmentController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager,
            IUnitOfWork unitOfWork, IUserStore<IdentityUser> userStore, IEmailSender emailSender,
            ApplicationDbContext dbContext)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _userStore = userStore;
            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
            _emailStore = GetEmailStore();
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var users = _dbContext.ApplicationUsers.ToList();
            return View(users);
        }

        public IActionResult Upsert(string userId)
        {
            var user = _dbContext.ApplicationUsers.FirstOrDefault(x => x.Id == userId);
            var roleList = _roleManager.Roles.Select(x => x.Name)
                .Select(i =>
                    new SelectListItem
                    {
                        Text = i,
                        Value = i
                    }
                );

            if (user is null)
            {
                return View(new UserUpsertVM()
                {
                    RoleList = roleList
                });
            }

            return View(new UserUpsertVM()
            {
                ApplicationUser = user,
                Role = string.Join(", ", _userManager.GetRolesAsync(user).GetAwaiter().GetResult()),
                RoleList = roleList
            });
        }

        [HttpPost]
        public async Task<IActionResult> Upsert(UserUpsertVM model)
        {
            var roleList = _roleManager.Roles.Select(x => x.Name)
                .Select(i =>
                    new SelectListItem
                    {
                        Text = i,
                        Value = i
                    }
                ).ToList();
            model.RoleList = roleList;
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = _dbContext.ApplicationUsers.FirstOrDefault(x => x.Id == model.ApplicationUser.Id);
            var update = true;
            if (user is null)
            {
                user = Activator.CreateInstance<ApplicationUser>();
                update = false;
            }

            user.FirstName = model.ApplicationUser.FirstName;
            user.LastName = model.ApplicationUser.LastName;
            user.Email = model.ApplicationUser.Email;

            await _userStore.SetUserNameAsync(user, model.ApplicationUser.Email, CancellationToken.None);
            await _emailStore.SetEmailAsync(user, model.ApplicationUser.Email, CancellationToken.None);

            IdentityResult result;
            if (update)
            {
                TempData["success"] = UserSuccessfullyUpdated;
                result = await _userManager.UpdateAsync(user);
            }
            else
            {
                var password = CreateRandomPassword();
                result = await _userManager.CreateAsync(user, password);

                if (string.IsNullOrEmpty(user.Email))
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    TempData["error"] = SendingInformationUserOrEventNotFound;
                    return View(model);
                }

                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { area = "Identity", code },
                    protocol: Request.Scheme);

                if (callbackUrl == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    TempData["error"] = SendingInformationUserOrEventNotFound;
                    return View(model);
                }

                await _emailSender.SendEmailAsync(
                    user.Email,
                    "New account create",
                    $"Your account have been prepared by admin of the website. <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>Click here to change password</a>.");

                TempData["success"] = UserSuccessfullyCreated;
            }

            if (result.Succeeded)
            {
                var role = _userManager.GetRolesAsync(user).ConfigureAwait(false).GetAwaiter().GetResult()
                    .SingleOrDefault();
                if (role is not null && role == model.Role!)
                {
                    return RedirectToAction(nameof(Index));
                }

                if (role is not null)
                {
                    await _userManager.RemoveFromRoleAsync(user, role);
                }
                await _userManager.AddToRoleAsync(user, model.Role ?? SD.Role_Customer);

                return RedirectToAction(nameof(Index));
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }


            TempData["success"] = "";
            TempData["error"] = UserFailedCreateOrUpdate;
            return View(model);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string? userId)
        {
            if (userId is null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = UserNotFound });
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user is null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = UserNotFound });
            }

            var listOfUserParticipation = _unitOfWork.EventParticipant.GetAllFiltered(x => x.UserId == userId).ToList();
            if (listOfUserParticipation.Count != 0)
            {
                _unitOfWork.EventParticipant.RemoveRange(listOfUserParticipation);
            }

            var deleteResult = await _userManager.DeleteAsync(user);

            if (!deleteResult.Succeeded)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = UserDeleteSomethingWrong });
            }

            await _dbContext.SaveChangesAsync();
            return Json(new { success = true, message = UserSuccessfullyDeleted });
        }

        private IUserEmailStore<IdentityUser> GetEmailStore()
        {
            if (!_userManager.SupportsUserEmail)
            {
                throw new NotSupportedException("The default UI requires a user store with email support.");
            }

            return (IUserEmailStore<IdentityUser>)_userStore;
        }

        private static string CreateRandomPassword(int length = 15)
        {
            const string smallLetters = "abcdefghijklmnopqrstuvwxyz";
            const string bigLetters = "ABCDEFGHJKLMNOPQRSTUVWXYZ";
            const string number = "0123456789";
            const string nonAlphanumeric = "!@#$%^&*?_-";
            const string validChars = bigLetters + smallLetters + number + nonAlphanumeric;
            var random = new Random();

            var chars = new char[length];
            for (var i = 0; i < length; i++)
            {
                if (!chars.Any(smallLetters.Contains))
                {
                    chars[i] = smallLetters[random.Next(0, smallLetters.Length)];
                    continue;
                }

                if (!chars.Any(bigLetters.Contains))
                {
                    chars[i] = bigLetters[random.Next(0, bigLetters.Length)];
                    continue;
                }

                if (!chars.Any(number.Contains))
                {
                    chars[i] = number[random.Next(0, number.Length)];
                    continue;
                }

                if (!chars.Any(nonAlphanumeric.Contains))
                {
                    chars[i] = nonAlphanumeric[random.Next(0, nonAlphanumeric.Length)];
                    continue;
                }

                chars[i] = validChars[random.Next(0, validChars.Length)];
            }

            return new string(chars);
        }
    }
}

EventManager/Areas/Customer/Controllers/EventParticipantsController.cs
using EventManager.DataAccess.Repository.IRepository;
using EventManager.Models;
using EventManager.Models.ViewModels;
using EventManager.Utils;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mime;
using static EventManager.Utils.Enums;
using static EventManager.Utils.TempDataInfos;

namespace EventManager.Areas.Customer.Controllers
{
    [Area(SD.Role_Customer)]
    public class EventParticipantsController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<EventParticipantsController> _logger;

        public EventParticipantsController(UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork, ILogger<EventParticipantsController> logger)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var eventsVM = new EventsVM
            {
                UserId = _userManager.GetUserId(User),
                Events = _unitOfWork.Event.GetAll().ToList(),
                EventParticipants = _unitOfWork.EventParticipant.GetAll().ToList()
            };

            return View(eventsVM);
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(string eventId)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user is null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = UserNotFound });
            }

            var selectedEvent = _unitOfWork.Event.Get(e => e.Id == eventId);
            if (selectedEvent is null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = EventNotFound });
            }

            var existingParticipant = _unitOfWork.EventParticipant.Get(ep => ep.EventId == eventId && ep.UserId == user.Id);
            if (existingParticipant is not null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = EventParticipantsAlreadySigned });
            }

            var newParticipant = new EventParticipant
            {
                EventId = eventId,
                UserId = user.Id,
                Status = AssignmentStatus.Applied
            };

            try
            {
                _unitOfWork.EventParticipant.Add(newParticipant);
                _unitOfWork.Event.Update(selectedEvent);
                _unitOfWork.Save();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Exception");
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, message = EventParticipantsError });
            }

            return Json(new { success = true, message = EventParticipantsSigned });
        }

        [HttpDelete]
        public IActionResult SignOut(string? userId, string? eventId)
        {
            var participant = _unitOfWork.EventParticipant.Get(x => x.UserId == userId && x.EventId == eventId);
            if(participant is null) 
            {
                return Json(new { success = false, message = EventParticipantsNotSignedUp });
            }

            _unitOfWork.EventParticipant.Remove(participant);
            _unitOfWork.Save();

            return Json(new { success = false, message = EventParticipantsSignedOut });
        }
    }
}

EventManager/Controllers/EventController.cs
using EventManager.DataAccess;
using EventManager.Models;
using Microsoft.AspNetCore.Mvc;

namespace EventManager.Controllers
{
    public class EventController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public EventController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var objEventList = _dbContext.Events.ToList();
            return View(objEventList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Event eventObj)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TempData["success"] = "Testowanie notyfikacji";
            _dbContext.Events.Add(eventObj);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(Guid? id)
        {
            if (!id.HasValue || id.Value == Guid.Empty)
            {
                return NotFound();
            }
            var eventFromDb = _dbContext.Events.FirstOrDefault(x => x.Id == id);
            if (eventFromDb == null)
            {
                return NotFound();
            }

            return View(eventFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Event eventObj)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            _dbContext.Events.Update(eventObj);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(Guid? id)
        {
            if (!id.HasValue || id.Value == Guid.Empty)
            {
                return NotFound();
            }

            var eventFromDb = _dbContext.Events.FirstOrDefault(x => x.Id == id);
            if (eventFromDb == null)
            {
                return NotFound();
            }

            return View(eventFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(Guid? id)
        {
            if (!id.HasValue || id.Value == Guid.Empty)
            {
                return View();
            }

            var eventFromDb = _dbContext.Events.FirstOrDefault(x => x.Id == id);
            if (eventFromDb == null)
            {
                return NotFound();
            }

            _dbContext.Events.Remove(eventFromDb);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

EventManager/Views/Shared/_Layout.cshtml
@{
    var isAdmin = User.IsInRole(SD.Role_Admin);
    var isCompany = User.IsInRole(SD.Role_Company);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EventManager.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="@("https://cdn.jsdelivr.net/npm/@sweetalert2/theme-dark/dark.css")">
    <link rel="stylesheet" href="~/lib/jquery-ui-1.13.2.custom/jquery-ui-1.13.2.custom/jquery-ui.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="EventParticipants" asp-action="Index">Events</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-area="@(isAdmin ? "Admin" : isCompany ? "Company" : "Customer")" asp-controller="Calendar" asp-action="Index">Calendar</a>
                        </li>
                        @if (isAdmin || isCompany)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Management</a>
                                <div class="dropdown-menu">
                                    
                                    <a class="nav-link" asp-area="@(isAdmin ? "Admin" : "Company")" asp-controller="Event" asp-action="Index">Events</a>
                                    
                                    @if (isAdmin)
                                    {
                                        <a class="nav-link" asp-area="Admin" asp-controller="UserManagment" asp-action="Index">Users</a>
                                    }
                                </div>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary text-center">
        <div class="container">
            <i class="bi bi-heart-fill"></i> 2023 - EventManager
        </div>
    </footer>
    <script src="https://cdn.tiny.cloud/1/ok8294vsq5i0kx5ehcak71ezjcdn21mre5nybatzefmp6pgf/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/lib/jquery-ui-1.13.2.custom/jquery-ui-1.13.2.custom/jquery-ui.min.js"></script>
    <script src=" https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.js "></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EventManager/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>   
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}